pipelines:
  Employees:
    group: apis
    materials:
      repo:
        git: https://github.com/exarcol/payroll.git
        branch: master
    stages:
      - Unit_Tests:
          jobs:
            run_tests:
              tasks:
                - exec:
                    command: mvn
                    arguments:
                      - clean
                      - test
      - Create_Uberjar:
          jobs:
            compile_to_Ubejar:
              artifacts:
                - build:
                    source: '**/swarm-1.0.war'
                    destination: target/
                - build:
                    source: '**/swarm-1.0-swarm.jar'
                    destination: target/
              tasks:
                - exec:
                    command: mvn
                    arguments:
                      - '-Dmaven.test.skip=true'
                      - clean
                      - package
                      - wildfly-swarm:package
      - Upload_to_loc:
          jobs:
            upload_to_loc:
              tasks:
                - fetch:
                    stage: Create_Uberjar
                    job: compile_to_Ubejar
                    source: target/target/swarm-1.0-swarm.jar
                    destination: app/
                    is_file: true
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - /godata/copy_local.sh
      - Deploy_on_loc:
          jobs:
            deploy_on_loc:
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - /godata/stop_server_local.sh
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - /godata/deploy_local.sh
      - Deploy_on_aws:
          jobs:
            deploy:
              tasks:
                - fetch:
                    stage: Create_Uberjar
                    job: compile_to_Ubejar
                    source: target/target/swarm-1.0-swarm.jar
                    destination: app_aws/
                    is_file: true
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - scp -i /godata/ssh_access.pem -o "StrictHostKeyChecking no" app_aws/swarm-1.0-swarm.jar ubuntu@ec2-52-14-114-20.us-east-2.compute.amazonaws.com:/tmp/ > /dev/null 2>&1 &
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - ssh -i /godata/ssh_access.pem -o "StrictHostKeyChecking no" ubuntu@ec2-52-14-114-20.us-east-2.compute.amazonaws.com 'kill $(pgrep java) || true'
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - ssh -i /godata/ssh_access.pem -o "StrictHostKeyChecking no" ubuntu@ec2-52-14-114-20.us-east-2.compute.amazonaws.com 'nohup  java -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -jar  /tmp/swarm-1.0-swarm.jar > /dev/null 2>&1 &'
